# Generated by Django 5.0.2 on 2024-06-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_b', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
    ]
