# Generated by Django 5.0.2 on 2024-06-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_b', '0003_customuser_profile_picture_customuser_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='worker_type',
            field=models.CharField(blank=True, choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('cleaner', 'Cleaner')], max_length=100, null=True),
        ),
    ]
